apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: example-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.19.255.200-172.19.255.250 # Adjust this to your Docker subnet!
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty-advertisement
  namespace: metallb-system
